### ISSUE TITLE
Feature suggestion : Allow the game to use another MIDI device.

### ISSUE THREAD

**Issue by HerosDuGouter** [Solanacean/GrimoireDigiMusicDLL#2]
Hello ! I am not sure it can be done, but I was wondering if you had plan to allow us to use the MIDI device of our choice in Grimoire so we can try various soundfonts/VST (Roland Sound Canvas VA for example). Currently it seems that even if you use Coolsoft Midi Mapper to change the default Windows Device, it is still using the one that ships with windows. 

We can of course convert a soundfont in the DLS format and replace the default soundfont, but it is a bit clunky and still does not allow to use VST's or physical MIDI device.

It would be great if we could use Loopmidi + Falcosoft Midi Player with Grimoire :)

Thank you for the work you have already done, it is great to have this MP3 option.
By the way, do you know where I can find .midi files from the game ? I tried the file extractor but apparently Cleve has added an encoding on his files and the extractor output files with the correct name and size but are unusable.

**Comment by Solanacean** [comment]
Hi and thank you for your kind words. =)

Well, yes, it is certainly doable. In fact, that was my original plan and before I decided to take the digital audio route I’ve cobbled up a prototype wrapper which forced a specific MIDI port on Grimoire. I thought I could kill two proverbial birds with one stone and please both the owners of real hardware synths and those who want to experiment with soundfonts. Unfortunately, it didn't work out quite so well.

There’s apparently some kind of a bug in CoolSoft’s VirtualMIDISynth which makes it loose connection with Grimoire soon after the game is launched. What happens is this: the game is started, the wrapper is loaded, the VirtualMIIDISynth’s port is opened - the message in VirtualMIDISynth’s log indicates that the connection is established, and then, few seconds later, poof - the connection is dropped and when the game finishes loading its resources and starts playing music you’re greeted with a dead silence. This (mis)behavior is seemingly unpredictable - sometimes you get lucky and the connection sticks, but most of the time it doesn’t. So this solution is totally unacceptable for soundfont users as it solves nothing for them.

Which still leaves the owners of hardware synths as well as the users of SC-VA. I’ve made a [video](https://www.youtube.com/watch?v=ksIu-IrAg2Y) showing Grimoire playing music through the wrapper using SAVIHost + SC-VA combo and though I don’t have a hardware synth, I imagine it would work fine for real devices as well. The thing is, the owners of hardware synths make a tiny fraction of Grimoire’s userbase and as for SC-VA, it's not an option for most people too - since Roland decided to switch to the subscription model you can't even buy it anymore. 

I was working on another wrapper with direct support of soundfonts, which didn’t rely on VirtualMIDISynth. [The prototype worked great,](https://www.youtube.com/watch?v=9G3mABMp7Hs) yet I've decided to put the work on hold and focus on adding support for digital audio instead as, frankly, I see it as the best solution for everyone. With digital audio you get almost everything. You can record the output of the real SC-88 or render game music to audio in a DAW using SC-VA as a software instrument (that’s what I intend to do) and feed it to the game - no need to tinker with SAVIHost and SC-VA each time you want to play. Unlike SAVIHost + SC-VA solution, it works for WINE users too. You can render MIDI to audio using the soundfont of your choice and use it in the game. And finally, when the long promised [orchestral remake](https://www.steamkiwi.com/article=151982/ellsworth-halls-orchestral-revisions-of-grimoire-classic-tunes) becomes available, you’ll be able to put it to use the same way too!

I've uploaded .mid files extracted from V2 [here.](https://drive.google.com/open?id=1wlbmlfsXHgsVymhHcapCp4CPbmdfxYiy)
